# Generated by Django 5.1.6 on 2025-04-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_managers_careerroadmap_milestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='target_date',
        ),
    ]
